POST http://localhost:5675/api/site/login
Accept: application/json
Content-Type: application/json

{
  "email": "another@gmail.com",
  "password": "Kavabunga243"
}
###

POST http://localhost:5675/api/site/signup
Accept: application/json
Content-Type: application/json

{
  "email": "another@gmail.com",
  "first_name": "Vanya",
  "last_name": "Pupkin",
  "password": "Kavabunga243"
}
###
DELETE http://localhost:5675/api/posts/7/delete
Accept: application/json
Content-Type: application/json
Authorization: Bearer bivkn6kPpzAAkrc_5_T4ymkNyt5CaUJt

###
DELETE http://localhost:5675/api/posts/2/comment-delete
Accept: application/json
Content-Type: application/json
Authorization: Bearer bivkn6kPpzAAkrc_5_T4ymkNyt5CaUJt

###
PUT http://localhost:5675/api/posts/8/update
Accept: application/json
Content-Type: application/json
Authorization: Bearer bivkn6kPpzAAkrc_5_T4ymkNyt5CaUJt

{
  "content": "Posting my posting"
}

###
PUT http://localhost:5675/api/posts/1/comment-update
Accept: application/json
Content-Type: application/json
Authorization: Bearer Ch6lM8qpSTUo_D4X8pwyo-MLxauSYoHg

{
  "name": "Commenting my commentiCh6lM8qpSTUo_D4X8pwyng"
}

###
POST http://localhost:5675/api/posts/8/share
Accept: application/json
Content-Type: application/json
Authorization: Bearer Ch6lM8qpSTUo_D4X8pwyo-MLxauSYoHg

{
  "reposters": ["3"]
}

###
POST http://localhost:5675/api/posts/8/star
Accept: application/json
Content-Type: application/json
Authorization: Bearer Ch6lM8qpSTUo_D4X8pwyo-MLxauSYoHg

###
DELETE http://localhost:5675/api/posts/8/un-star
Accept: application/json
Content-Type: application/json
Authorization: Bearer Ch6lM8qpSTUo_D4X8pwyo-MLxauSYoHg

###
POST http://localhost:5675/api/profile/2/subscribe
Accept: application/json
Content-Type: application/json
Authorization: Bearer Ch6lM8qpSTUo_D4X8pwyo-MLxauSYoHg

###
DELETE http://localhost:5675/api/profile/2/un-subscribe
Accept: application/json
Content-Type: application/json
Authorization: Bearer Ch6lM8qpSTUo_D4X8pwyo-MLxauSYoHg

###
GET http://localhost:5675/api/profile/2/view
Accept: application/json
Content-Type: application/json

###
GET http://localhost:5675/api/profile/settings
Accept: application/json
Content-Type: application/json
Authorization: Bearer Ch6lM8qpSTUo_D4X8pwyo-MLxauSYoHg

###
GET http://localhost:5675/api/profile/starred
Accept: application/json
Content-Type: application/json
Authorization: Bearer Ch6lM8qpSTUo_D4X8pwyo-MLxauSYoHg

###
PUT http://localhost:5675/api/profile/1/update
Accept: application/json
Content-Type: application/json
Authorization: Bearer bivkn6kPpzAAkrc_5_T4ymkNyt5CaUJt

{
  "first_name": "VASILI"
}

###
POST http://localhost:5675/api/posts/8/create-comment
Accept: application/json
Content-Type: application/json
Authorization: Bearer bivkn6kPpzAAkrc_5_T4ymkNyt5CaUJt

{
  "name": "Comment"
}
